version: "3.9"

services:
  test:
    build:
      context: ..
      dockerfile: docker/Dockerfile_test
    command: pytest
    volumes:
      - .:/code
    environment:
      - DJANGO_SETTINGS_MODULE=Cars.test_settings
    depends_on:
      - db
  db:
    image: postgres:13.9
    volumes:
      - /app:/var/lib/postgresql/data_app_test
    env_file:
      - ../env_files/db-variables.env
    ports:
      - "5432:5432"
  web:
    build:
      context: ..
      dockerfile: docker/Dockerfile_test
    volumes:
      - .:/code
    ports:
      - '8000:8000'
    depends_on:
      - db

  celery_worker:
    container_name: celery_worker
    build:
      context: ..
      dockerfile: docker/Dockerfile_test
    volumes:
      - .:/code
    command: celery -A Cars worker -l info
    depends_on:
      - rabbitmq
      - web
    links:
      - rabbitmq
  rabbitmq:
    container_name: rabbitmq
    hostname: rabbit
    image: rabbitmq:3-management
    ports:
      - "5673:5673"
      - "15672:15672"  # here, we can access rabbitmq management plugin

volumes:
  data_app_test:
