version: "3.9"

services:
  db:
    image: postgres:13.9
    volumes:
      - /app:/var/lib/postgresql/data_app
    env_file:
      - ../env_files/db-variables.env
    ports:
      - "5432:5432"
  web:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    volumes:
      - .:/code
    ports:
      - '8000:8000'
    depends_on:
      - db

  celery_worker:
    container_name: celery_worker
    build:
      context: ..
      dockerfile: docker/Dockerfile
    volumes:
      - .:/code
    command: celery -A Cars worker -l info
    depends_on:
      - rabbitmq
      - web
    links:
      - rabbitmq
#
#  celery_beat_worker:
#    container_name: celery_beat_worker
#    build:
#      context: ..
#      dockerfile: docker/Dockerfile
#    volumes:
#      - .:/code
#    command: celery -A Cars beat -l info
#    depends_on:
#      - rabbitmq
#      - web
#    links:
#      - rabbitmq
#
#  flower:
#    image: mher/flower
#    command: celery --broker=amqp://user:bitnami@rabbitmq:5672//
#    ports:
#      - "8888:8888"
#    depends_on:
#      - rabbitmq
#
  rabbitmq:
    container_name: rabbitmq
    hostname: rabbit
    image: rabbitmq:3-management
    ports:
      - "5673:5673"
      - "15672:15672"  # here, we can access rabbitmq management plugin
