FROM python:3.10.6-alpine
ENV PYTHONUNBUFFERED=1
WORKDIR /test/
RUN apk update && apk add postgresql-dev gcc python3-dev musl-dev
COPY Pipfile .
COPY Pipfile.lock .
COPY test_entrypoint.sh .
RUN chmod +x test_entrypoint.sh
RUN python -m pip install --upgrade pip
RUN pip install pipenv
RUN pipenv install --dev --system --deploy
COPY . .
#CMD ["python", "manage.py", "makemigrations"]
#CMD ["python", "manage.py", "migrate"]
#CMD ["python", "manage.py", "makemigrations","&&","migrate", "&&", "runserver", "0.0.0.0:8000"]
ENTRYPOINT ["./test_entrypoint.sh"]